services:
  angular-app:
    build: .
    image: angular11-node12
    container_name: front-cotizacion
    working_dir: /app
    volumes:
      - ./front-cotizacion:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install && ng serve --host 0.0.0.0 --poll 2000"